[workspace]
members = [
	"crates/rxyz",
	"crates/xtask"
]

excludes = [
	"renderling"
]

resolver = "2"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
log = "0.4.21"
serde = "1.0.203"
serde_yaml = "0.9.34"
snafu = "0.8.3"
