[package]
name = "rxyz"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-lite = "2.3.0"
html_parser = "^0.7"
http = "1.1.0"
log = {workspace=true}
markdown = "1.0"
mogwai = "0.7"
serde = {workspace=true}
serde_yaml = {workspace=true}
snafu = {workspace=true}
syntect = "5.2"
